version: "2"
services:
  app:
    container_name: ambev-api
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - .:/usr/src/app
    command: nodemon server.js
    depends_on:
     - database
    links:
      - 'database'
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - './docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    environment:
      MYSQL_ROOT_PASSWORD: YW1iZXY6YW1iZXZQcm9jZXNzMjAyMEBA
      MYSQL_DATABASE: ambev_development
      MYSQL_USER: ambev
      MYSQL_PASSWORD: Amb3v123
    ports:
      - "3306:3306"

volumes:
  db_data:
  notused: